### ISSUE TITLE
Definir renderização de view

### ISSUE THREAD

**Issue by TiagoGouvea** [DesafioDoCodigo/desafio-do-codigo#16]
## O que deseja criar
- [x] Discussão

## Resultado esperado
Definir quais ferramentas e padrões usarmos para a renderização de HTML, de forma a ficar separado das regras de negócios mais complexas, facilitando a manutenção.

## Como isso é hoje?
Hoje cada arquivo vai "dando echo" do HTML, ou é basicamente um arquivo HTML com blocos de PHP no meio dele.

## Detalhe o que deve ser feito o máximo que puder
Gostaria de discutir qual biblioteca podemos usar, que seja simples, de código limpo e fácil de aprender. Veja a discussão semelhante em #15.
Como você acha que poderia ser? O que já usou e que gostou? Como podemos fazer?
Diz ai!

**Comment by mathmarques** [comment]
Eu utilizo bastante o [Smarty](https://github.com/smarty-php/smarty/), a syntax é bem simples e permite extender templates, além de ser rápido no que faz.
Mas o [Twig](https://twig.symfony.com/) é uma ótima opção também, e acredito que um dos mais utilizados hoje em dia.
Acredito que os dois sejam uma ótima opção e não consigo achar um caso de uso em que um seja bom e o outro não.

**Comment by TiagoGouvea** [comment]
@mathmarques usei MUITO o smarty já. Na epoca até encontrei uns bugs e reportei. Isso foi em 2008. Já usei o Twig também.

Dentre os dois, simpatizo mais com o Twig, porque me parece que o código dele é mais enxuto e atual.

Achei agora aqui [este comparativo](https://www.freelancinggig.com/blog/2017/03/25/pros-cons-twig-vs-smarty-web-templates/) que de alguma forma também disso isso.

Outra vantagem é que o twig não exige tanta implementação pra funcionar, então mantem o código bem limpo né.. tanto "de quem chama", quanto na view mesmo.

**Comment by mathmarques** [comment]
@TiagoGouvea De fato o Twig é mais atual e possui um código mais legível. Concordo que é uma boa escolha!

**Comment by TiagoGouvea** [comment]
O @mathmarques implementou o Twig no código novo agora a pouco. Vamos seguir então desta maneira, com Twig.
Grato a todos pela colaboração!
