### ISSUE TITLE
Definir padrão do projeto

### ISSUE THREAD

**Issue by TiagoGouvea** [DesafioDoCodigo/desafio-do-codigo#17]
Para criar uma issue, informe as três informações abaixo, e apague este parágrafo aqui. Marque um X onde estiver [ ] para marcar como verdadeiro. 

## O que deseja criar
- [X] Discussão

## Resultado esperado
Definir de que forma o código será organizado, para que todos possam trabalhar nele sem problemas. Importante ressaltar que o código precisa ser limpo, sem frameworks complexos, para permitir que jovens que estão começando a programar, possam pegar issues e implementa-las.
**Simplicidade**, é a palavra chave importante aqui.

## Como isso é hoje?
Não existe padrão. Os arquivos php estão espalhados em várias páginas, um arquivo func.php tem um monte de códigos soltos, sem comentários, sem documentação.. 

## Detalhe o que deve ser feito o máximo que puder
Proponho essa discussão, de qual padrão seguir. Precisa mesmo ser simples e acessível.
O que você propõe?

**Comment by mathmarques** [comment]
Acredito que o [Slim Framework](https://www.slimframework.com/) se encaixa bastante no propósito de ser simples. Ele é basicamente um roteador com um container de dependências e algumas funções que facilitam o desenvolvimento e a organização do projeto. Ele não força nenhuma estrutura e nem tem muitas dependências, então da para organizar na maneira que preferir.
Eu por exemplo costumo, com o Slim, seguir o estrutura/padrão:
```
/
|--- app/
|      |--- src/
|      |      |--- Controller
|      |      |--- Model
|      |      |--- Middleware
|      |      |--- Persistence
|      |--- templates/
|      |--- dependencies.php
|      |--- routes.php
|      |--- settings.php
|--- public/
|      |--- css/
|      |--- js/
|      |--- index.php
```

**Comment by TiagoGouvea** [comment]
Entendi @mathmarques .

Você acha que o projeto inteiro poderia estar sendo carregado pelo slim?

Já usei o slim pra API, e tem sido ótimo. Mas nunca pro projeto todo.. é de boa né?

Se optarmos pelo Slim, você toparia pegar pra criar essa estrutura inicial?

**Comment by mathmarques** [comment]
@TiagoGouvea 
O Slim aguenta de boa, ele é bem leve mesmo!

Essa semana eu vou iniciar um sistema com base no Slim, dai posso aproveitar e criar e estrutura inicial aqui também sem problemas!

**Comment by Tagliatti** [comment]
Eu sou a favor de usar Laravel, bem mais rápido pra desenvolver e é o framework mais utilizado disparado no momento. Tem uma documentação que permite com que quem nunca usou se torne intimo bem rápido. Outra vantagem é que não precisa usar tudo que que o framework oferece, usa o que precisa, ou o que o programador conhece dele.
Acho que o ponto mais importante em usa-lo é o fato de que uma pessoa que está querendo programar em PHP vai poder aprender o framework que vei provavelmente ajudar ele até a conseguir um emprego.

**Comment by TiagoGouvea** [comment]
@Tagliatti eu uso o Laravel em um projeto grande que tenho, usei o symfony por anos, era até o moderador do fórum oficial naquela época.
Não consigo imaginar uma pessoa "novata" na programação chegando no symfony, e encontrando onde ficam as coisas com facilidade, ou até, entendendo como ele funciona.
O Desafio do Código é um programa para incentivar as pessoas a aprenderem programação, e seria incrível realmente se essas pessoas pudessem, em algum momento, pegar uma issue aqui pra fazer. Acho que é um desejo distante, mas acho que sendo laraval ficaria mais distante ainda.
O Desafio do Código, é agnóstico de linguagem, até porque não é ensinado apenas programação, é ensinado matemática e inglês também.
Reforçando, acho o Laravel incrível! Mas pra esse projeto estou concordando com o @mathmarques e pensando que o caminho seja realmente o Slim.

@mathmarques vou querer sim que você faça essa estrutura básica quando quiser. Por ser algo que acho essencial para o futuro do projeto, se quiser, podemos até fazer juntos. O que acha?

Grato pela colaboração galera!

**Comment by mathmarques** [comment]
@TiagoGouvea Podemos sim! Oq acha de criar uma nova branch limpa aqui com a reformulação do app?

**Comment by TiagoGouvea** [comment]
@mathmarques otima ideia! Assim, conforme as pessoas forem levando os códigos de um branch pro outro, vai limpando, organizando.

**Comment by TiagoGouvea** [comment]
Criamos a nova estrutura agora pro projeto, e colocamos o código antigo na branch **desafioAntigo**. Amanhã devo passar ajustando algumas coisas e criando as issues de migração e atualização de código.
Valeu @mathmarques pela força!

**Comment by TiagoGouvea** [comment]
Vou fechar por aqui, e focar na #15.
